name: Build and Deploy
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  defaults:
    run:
      working-directory: backend
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repo
    - name: Set sha_short
      id: vars
      run: |-
        echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        # Set default branch name for PRs, as we still want to test build an image on PRs
        # but we have no branch to set a tag for.
        branch="test"
        if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
          branch="${GITHUB_REF#refs/heads/}"
        fi
        echo "branch=${branch}" >> $GITHUB_ENV
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Install go dependencies
      run: go get -v ./...
    - name: Set Tag in env variable
      run: |
        echo "${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}" > APP_NAME
        echo "$GITHUB_SHA" > TAG
    - name: Build Image
      run: docker build . --file Dockerfile --tag $(cat APP_NAME):$(cat TAG)
    - name: Tag the image to latest
      run: docker tag $(cat APP_NAME):$(cat TAG) $(cat APP_NAME):latest
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Image push
      run: docker push $(cat APP_NAME):latest