name: Build and Deploy
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
      -

working-directory: backend

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repo
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install go dependencies
        run: go get -v ./...
      - name: Set Tag in env variable
        run: |
          echo "${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}" > APP_NAME
          echo "$GITHUB_SHA" > TAG
      - name: Build Image
        run: docker build . --file Dockerfile --tag $(cat APP_NAME):$(cat TAG)
      - name: Tag the image to latest
        run: docker tag $(cat APP_NAME):$(cat TAG) $(cat APP_NAME):latest
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Image push
        run: docker push $(cat APP_NAME):latest